
language: python

install:
 - git fetch -t
 - pip install Sphinx

script:
 - make html
 - touch _build/html/.nojekyll

deploy:
 - provider: pages:git
   verbose: true
   token: $GITHUB_TOKEN
   edge: true
   keep_history: false
   local_dir: _build/html
