
language: python

install:
 - git fetch -t
 - pip install Sphinx

script:
 - make html
 - touch _build/html/.nojekyll

deploy:
 - provider: pages
   skip_cleanup: true
   keep_history: false
   local_dir: _build/html
